apiVersion: v1
kind: Service
metadata:
  name: mq-replication-loadbalancer
  namespace: prod-mq
spec:
  type: LoadBalancer
  ports:
    - name: mq-traffic
      port: 1414
      targetPort: 1414
      protocol: TCP
  selector:
    app.kubernetes.io/component: integration
    app.kubernetes.io/instance: vks-prod-nativeha-mq2
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: ibm-mq
