# Generate the tls key pair using this command with your desired FQDN
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#  -keyout "tls.key" \
#  -out "tls.crt" \
#  -subj "/CN=qm-console.example.com" \
#  -addext "subjectAltName=DNS:qm-console.example.com"
#
# Update the tls.crt and tls-key sections below with the generated certificates
apiVersion: v1
kind: Secret
metadata:
  name: mq-console-tls-secret
  namespace: tanzu-system-ingress
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkSgAwIBAgIJAJ...
    [PASTE_CONTENTS_OF_MQ-TEST.CRT_HERE]
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEwAIBADANBgkqhkiG9w...
    [PASTE_CONTENTS_OF_MQ-TEST.KEY_HERE]
    -----END PRIVATE KEY-----