apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: vks-prod-nativeha-mq
  namespace: prod-mq
spec:
  # License Agreement (Change license string depending on your MQ version)
  license:
    accept: true
    license: {redacted}

  # Queue Manager Engine Configuration
  version: "10.0.0.0-r1"
  
  # Forces the kubelet to recursively change group permissions of mounted
  # ext4 volumes to GID 1001, allowing the MQ container to write data.
  securityContext:
    fsGroup: 1001

  queueManager:
    name: "haqueuemgr"
    # Activates the Raft consensus engine and automatically schedules exactly 3 Pods
    availability:
      type: NativeHA
      # Optional: You can add an inter-pod TLS secret below to encrypt replication traffic
      # tls:
      #   secretName: mq-internal-replication-tls

    # --- CRITICAL VKS OVERRIDES ---
    # Disables native OpenShift routing resources which break on raw Kubernetes/EKS
    route:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: false

    # Dedicated High-Performance Production Storage
    storage:
      defaultClass: "vks-primary-sp" # Set to your low-latency block storage class

      # Core state storage
      queueManager:
        type: persistent-claim
        size: 1Gi

      # Dedicated volume for active transaction and message payload persistence
      persistedData:
        enabled: true
        type: persistent-claim
        size: 1Gi

      # Dedicated volume for Write-Ahead Transaction Logs (Highly recommended for Native HA performance)
      recoveryLogs:
        enabled: true
        type: persistent-claim
        size: 1Gi

  # Web Console Customization
  web:
    enabled: true
    # VKS override: Prevents the creation of an OpenShift Route resource for the console
    route:
      enabled: false
    console:
      authentication:
        provider: manual
      authorization:
        provider: manual
    manualConfig:
      configMap:
        name: mqwebuserconfigmap
