apiVersion: v1
kind: ConfigMap
metadata:
  name: global-ha-autocluster-config
  namespace: prod-mq
data:
  autocluster.ini: |
    AutoCluster:
      Type=Uniform
      ClusterName=GLOBAL_HA_CLUSTER
      Repository1Name=QM1
      Repository1Conname=qm1-clustera.example.com(1414)
      Repository2Name=QM2
      Repository2Conname=qm2-clusterb.example.com(1414)
  uniform.mqsc: |
    DEFINE CHANNEL('+AUTOCL+_+QMNAME+') CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CONNAME('+CONNAME+') CLUSTER('+AUTOCL+') REPLACE
    DEFINE QLOCAL(APP.WORK.QUEUE) CLUSTER('+AUTOCL+') DEFBIND(NOTFIXED) REPLACE

