kind: ConfigMap
apiVersion: v1
metadata:
  name: mqwebuserconfigmap
  namespace: prod-mq
data:
  mqwebuser.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <server>
      <featureManager>
        <feature>appSecurity-2.0</feature>
        <feature>basicAuthenticationMQ-1.0</feature>
      </featureManager>
      <enterpriseApplication id="com.ibm.mq.console">
        <application-bnd>
          <security-role name="MQWebAdmin">
            <group name="MQWebAdminGroup" realm="defaultRealm"/>
          </security-role>
        </application-bnd>
      </enterpriseApplication>
      <basicRegistry id="basic" realm="defaultRealm">
        <user name="admin" password="Passw0rd!"/>
        <group name="MQWebAdminGroup">
          <member name="admin"/>
        </group>
      </basicRegistry>
    </server>
---
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: vks-prod-nativeha-mq2
  namespace: prod-mq
spec:
  version: "10.0.0.0-r1"
  # Forces the kubelet to recursively change group permissions of mounted
  # ext4 volumes to GID 1001, allowing the MQ container to write data.
  securityContext:
    fsGroup: 1001
  license:
    accept: true
    use: Development
    license: {redacted}
  queueManager:
    name: "QM2"
    availability:
      type: NativeHA
    ini:
      - configMap:
          name: global-ha-autocluster-config
          items:
            - autocluster.ini
    mqsc:
      - configMap:
          name: global-ha-autocluster-config
          items:
            - uniform.mqsc
    #  VKS OVERRIDES
    # Disables native OpenShift routing resources which break on raw Kubernetes/EKS
    route:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: false
    storage:
      queueManager:
        type: persistent-claim
        class: vks-primary-sp
        size: 2Gi
        deleteClaim: true
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi
 # Web Console Customization
  web:
    enabled: true
    # VKS override: Prevents the creation of an OpenShift Route resource for the console
    route:
      enabled: false
    console:
      authentication:
        provider: manual
      authorization:
        provider: manual
    manualConfig:
      configMap:
        name: mqwebuserconfigmap
  template:
    pod:
      containers:
        - name: qmgr
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            capabilities:
              drop:
                  - ALL

