apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: mq-cluster-b
  namespace: tenant-a-prod-ns-f88f5
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 198.51.100.0/20
    services:
      cidrBlocks:
      - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    classRef:
      name: builtin-generic-v3.6.0
      namespace: vmware-system-vks-public
    version: v1.35.5---vmware.1-vkr.1
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
      - class: node-pool
        name: worker-pool-1
        replicas: 3
        # --- Corrected v1beta2 Node Pool Variable Overrides ---
        variables:
          overrides:
          - name: vmClass
            value: best-effort-large
    variables:
    - name: storageClass
      value: vks-primary-sp
    - name: vmClass
      value: best-effort-medium
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: mq-cluster-b-cert-manager
  namespace: tenant-a-prod-ns-f88f5
spec:
  addonRef:
    name: cert-manager
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: mq-cluster-b
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: mq-cluster-b-contour
  namespace: tenant-a-prod-ns-f88f5
spec:
  addonRef:
    name: contour
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: mq-cluster-b
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  name: mq-cluster-b-contour
  namespace: tenant-a-prod-ns-f88f5
  annotations:
    clusteraddon.addons.kubernetes.vmware.com/owned-for-deletion: "true"
spec:
  values:
    infrastructure_provider: vsphere
    namespace: tanzu-system-ingress
    contour:
      configFileContents:
        gateway:
          gatewayRef:
            name: contour
            namespace: tanzu-system-ingress
      useProxyProtocol: false
      replicas: 2
      logLevel: info
    envoy:
      service:
        type: LoadBalancer
        annotations: {}
        externalTrafficPolicy: Cluster
        disableWait: false
      hostPorts:
        enable: true
        http: 80
        https: 443
      hostNetwork: false
      terminationGracePeriodSeconds: 300
      logLevel: info
    certificates:
      caDuration: 8760h
      caRenewBefore: 720h
      leafDuration: 720h
      leafRenewBefore: 360h
